config/routes.rb
Rails.application.routes.draw do
  resources :tours do
    collection do
      get :search
    end
  end
  resources :routes
  resources :excursions
  resources :cities
  resources :role_users
  resources :roles
  resources :password_resets

  get 'welcome/index', as: :welcome
  get 'welcome/insufficient_privileges', as: :ip
  get 'login' => 'welcome#new', :as => :login
  get 'logout' => 'welcome#destroy', :as => :logout
  post 'try_login' => 'welcome#create', :as => :try_login
  root 'welcome#index'

  resources :users do
    member do
      get :activate
    end
  end

end

app/models/tour.rb
class Tour < ActiveRecord::Base
  belongs_to :route
  accepts_nested_attributes_for :route
  
  validates :start_date, presence: true
  validates :days_in_tour, presence: true, numericality: {greater_than_or_equal_to: 1}
  validates :route, presence: true
  validates :add_price, presence: true, numericality: {greater_than_or_equal_to: 1}
  validates :add_descr, presence: true
  
  def value_for(str1, str2)
    if !(params[str1].nil?)
      if !(params[str1][str2].nil?)
        return params[str1][str2]
      end
    end
    return nil
  end
  
  def self.search(params)
    result = [[],[]]
    result[1] = Tour.eager_load(:route, route: :city)
    if !(params["search"].nil?)
      params["search"].each do |p|
        if !(p[1].empty?)
          arr = p[0].delete("01").split(".").map{|x| x.to_s}
          str = ": "
          str = " >= "if p[0].include?("0")
          str = " <= "if p[0].include?("1")
          result[0] << ["activerecord.models.#{arr[0]}", "activerecord.attributes.#{p[0].delete("01")}", str, p[1]]
        end
      end
    
      if !(params['search']['tour.start_date0'].nil?) and !(params['search']['tour.start_date0'].empty?)
        arr = params['search']['tour.start_date0'].split('.').map{|n| n.to_s}
        result[1] = result[1].where("start_date >= ?", "#{arr[2]}-#{arr[1]}-#{arr[0]}")
      end
    
      if !(params['search']['tour.start_date1'].nil?) and !(params['search']['tour.start_date1'].empty?)
        arr = params['search']['tour.start_date1'].split('.').map{|n| n.to_s}
        result[1] = result[1].where("start_date <= ?", "#{arr[2]}-#{arr[1]}-#{arr[0]}")
      end
    
      if !(params['search']['tour.days_in_tour0'].nil?) and !(params['search']['tour.days_in_tour0'].empty?)
        result[1] = result[1].where("days_in_tour >= ?", params['search']['tour.days_in_tour0'].to_i)
      end
    
      if !(params['search']['tour.days_in_tour1'].nil?) and !(params['search']['tour.days_in_tour1'].empty?)
        result[1] = result[1].where("days_in_tour <= ?", params['search']['tour.days_in_tour0'].to_i)
      end
    
      if !(params['search']['tour.add_price0'].nil?) and !(params['search']['tour.add_price0'].empty?)
        result[1] = result[1].where("add_price >= ?", params['search']['tour.add_price0'].to_i)
      end
    
      if !(params['search']['tour.add_price1'].nil?) and !(params['search']['tour.add_price1'].empty?)
        result[1] = result[1].where("add_price <= ?", params['search']['tour.add_price1'].to_i)
      end
    
      if !(params['search']['tour.add_descr'].nil?) and !(params['search']['tour.add_descr'].empty?)
        result[1] = result[1].where("add_descr ilike ?", "%#{params['search']['tour.add_descr']}%")
      end
    
      if !(params['search']['route.name'].nil?) and !(params['search']['route.name'].empty?)
        result[1] = result[1].where("routes.name ilike ?", "%#{params['search']['route.name']}%")
      end
    
      if !(params['search']['route.descr'].nil?) and !(params['search']['route.descr'].empty?)
        result[1] = result[1].where("routes.descr ilike ?", "%#{params['search']['route.descr']}%")
      end
    
      if !(params['search']['route.base_price0'].nil?) and !(params['search']['route.base_price0'].empty?)
        result[1] = result[1].where("routes.base_price >= ?", params['search']['route.base_price0'].to_i)
      end
    
      if !(params['search']['route.base_price1'].nil?) and !(params['search']['route.base_price1'].empty?)
        result[1] = result[1].where("routes.base_price <= ?", params['search']['route.base_price1'].to_i)
      end
    
      if !(params['search']['city.name'].nil?) and !(params['search']['city.name'].empty?)
		q = City.where("name = '#{params['search']['city.name']}'").ids
        result[1] = result[1].where("routes.city_id in (?)", q.join(','))
      end
    end
    return result
  end
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  before_action :set_tour, only: [:show, :edit, :update, :destroy]
  
  def search
    @result = Tour.search(params)
  end

  # GET /tours
  # GET /tours.json
  def index
    @tours = Tour.all
  end

  # GET /tours/1
  # GET /tours/1.json
  def show
  end

  # GET /tours/new
  def new
    @tour = Tour.new
    @tour.build_route.build_city
  end

  # GET /tours/1/edit
  def edit
  end

  # POST /tours
  # POST /tours.json
  def create
    @tour = Tour.new(tour_params)
#    raise "#{params}"
    
    flag = true
    flag1 = true
    if !(params["tour"]["route_id"].empty?)
      @tour.route_id = params["tour"]["route_id"].to_i
    else
      route = Route.new
      route.name = params["tour"]["route_attributes"]["name"]
      route.base_price = params["tour"]["route_attributes"]["base_price"].to_i
      route.descr = params["tour"]["route_attributes"]["descr"]
      
      if !(params["tour"]["route_attributes"]["city_id"].empty?)
        route.city_id = params["tour"]["route_id"].to_i
      else
        city = City.new
        city.name = params["tour"]["route_attributes"]["city_attributes"]["name"]
        flag1 = false if !(city.save)
        route.city = city
      end
      
      flag = false if !(route.save)
      @tour.route = route
    end

    respond_to do |format|
      if flag1 and flag and @tour.save
        format.html { redirect_to @tour, notice: 'Тур успешно создан.' }
        format.json { render :show, status: :created, location: @tour }
      else
        format.html { render :new }
        format.json { render json: @tour.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tours/1
  # PATCH/PUT /tours/1.json
  def update
    respond_to do |format|
      if @tour.update(tour_params)
        format.html { redirect_to @tour, notice: 'Тур успешно изменен.' }
        format.json { render :show, status: :ok, location: @tour }
      else
        format.html { render :edit }
        format.json { render json: @tour.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tours/1
  # DELETE /tours/1.json
  def destroy
    @tour.destroy
    respond_to do |format|
      format.html { redirect_to tours_url, notice: 'Тур успешно удален.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tour
      @tour = Tour.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tour_params
      params.require(:tour).permit(:start_date, :days_in_tour, :route_id, :add_price, :add_descr,
      route_attributes: [:id, :name, :base_price, :descr, :city_id,
      city_attributes: [:name]])
    end
end

app/helpers/tours_helper.rb
module ToursHelper

  def value_for(str1, str2)
    if !(params[str1].nil?)
      if !(params[str1][str2].nil?)
        return params[str1][str2]
      end
    end
    return nil
  end

end

app/views/tours/_city_fields.html.haml
.row
  .col-md-6
    .form-group
      = crf.label City.human_attribute_name(:name)
      = crf.text_field :name, class: 'form-control'
      = crf.error_messages_for(:name)

app/views/tours/_form.html.haml
= form_for @tour do |f|
  = error_messages_for @tour
  .row
    .col-md-6
      .form-group
        = f.label :start_date
        .input-group.date.datepicker
          = f.text_field(:start_date, value: lnil(f.object.start_date),
          class: 'form-control')
          %span.input-group-addon
            %span.glyphicon.glyphicon-calendar
        = f.error_messages_for(:start_date)
  .row
    .col-md-6
      .form-group
        = f.label :days_in_tour
        = f.number_field :days_in_tour, class: 'form-control'
        = f.error_messages_for(:days_in_tour)
  .panel.panel-wave
    .panel-heading
      = f.label "Маршрут"
    .panel-body
      = f.collection_select :route_id, Route.all, :id, :name, {include_blank: true}, {id: 'route_select'}
      = f.error_messages_for(:route_id)
      = f.fields_for :route, f.object.route || f.object.build_route do |rf|
        %fieldset#route-fieldset{"data-content" => "#{render "route_fields", rf: rf}"}
          %div#route-fields
            Выбран существующий маршрут
  .row
    .col-md-6
      .form-group
        = f.label :add_price
        = f.text_field :add_price, class: 'form-control'
        = f.error_messages_for(:add_price)
  .row
    .col-md-6
      .form-group
      = f.label :add_descr
      = f.text_area :add_descr, class: 'form-control'
      = f.error_messages_for(:add_descr)
  .form-actions
    = f.submit nil, class: 'btn btn-primary'

app/views/tours/_route_fields.html.haml
.row
  .col-md-6
    .form-group
      = rf.label Route.human_attribute_name(:name)
      = rf.text_field :name, class: 'form-control'
      = rf.error_messages_for(:name)
.row
  .col-md-6
    .form-group
      = rf.label Route.human_attribute_name(:base_price)
      = rf.number_field :base_price, class: 'form-control'
      = rf.error_messages_for(:base_price)
.panel.panel-wave
  .panel-heading
    = rf.label "Город"
  .panel-body
    = rf.collection_select :city_id, City.all, :id, :name, {include_blank: true}, {id: 'city_select'}
    = rf.error_messages_for(:city_id)
    = rf.fields_for :city, rf.object.city || rf.object.build_city do |crf|
      %fieldset#city-fieldset{"data-content" => "#{render "city_fields", crf: crf}"}
        %div#city-fields
          Выбран существующий город
.row
  .col-md-6
    .form-group
      = rf.label Route.human_attribute_name(:descr)
      = rf.text_area :descr, class: 'form-control'
      = rf.error_messages_for(:descr)

app/views/tours/edit.html.haml
- if is_admin?
  =breadcrumb_tag do
    %li.active
      База данных
    %li
      = link_to 'Туры', tours_path
    %li
      = t('headers.tours.edit')

  %h1= t('headers.tours.edit')

  = render 'form'
- else
  %h1= t('helpers.denied')

app/views/tours/index.html.haml
- if is_admin?
  =breadcrumb_tag do
    %li.active
      База данных
    %li
      = link_to 'Туры', tours_path
    
.page-header
  %h1= t('headers.tours.index')

%table.table.table-hover.table-striped
  - if is_admin?
    %caption
      = link_to new_tour_path, class: 'btn btn-success' do
        = fa_icon :plus
        = t('buttons.new.tour')
  %thead
    %tr
      %th= Tour.human_attribute_name(:start_date)
      %th= Tour.human_attribute_name(:days_in_tour)
      %th= Tour.human_attribute_name(:route)
      %th Общая цена
      %th= Tour.human_attribute_name(:add_descr)
      %th

  %tbody
    - @tours.each do |tour|
      %tr
        %td.center{data: {label: Tour.human_attribute_name(:start_date)}}
          = lnil(tour.start_date)
        %td.center{data: {label: Tour.human_attribute_name(:days_in_tour)}}
          = tour.days_in_tour
        %td.center{data: {label: Tour.human_attribute_name(:route)}}
          = tour.route.name
        %td.center{data: {label: "Общая цена"}}
          = tour.add_price + tour.route.base_price
        %td.center{data: {label: Tour.human_attribute_name(:add_descr)}}
          = tour.add_descr
        %td.right
          = link_to tour, class: 'btn btn-warning' do
            = fa_icon :eye
            = t('buttons.show')
          - if is_admin?
            = link_to edit_tour_path(tour), class: 'btn btn-info' do
              = fa_icon :edit
              = t('buttons.edit')
          - if is_admin?
            = link_to tour, :method => :delete, 
            :data => { :confirm => t('buttons.confirm.tour') }, 
            class: 'btn btn-danger' do
              = fa_icon :times
              = t('buttons.destroy')

app/views/tours/new.html.haml
- if is_admin?
  =breadcrumb_tag do
    %li.active
      База данных
    %li
      = link_to 'Туры', tours_path
    %li
      = t('headers.tours.new')

  .page-header
    %h1= t('headers.tours.new')

  = render 'form'
- else
  %h1= t('helpers.denied')

app/views/tours/search.html.haml
.page-header
  %h1 Параметры поиска
  
= form_tag search_tours_path(), method: :get do
  
  .panel.panel-wave
    .panel-heading
      Тур
    .panel-body
      .row
        .col-md-6
          .form-group
            = label_tag(Tour.human_attribute_name(:start_date))
      .row
        .col-md-6
          .form-group
            = label_tag("От")
            .input-group.date.datepicker
              = text_field_tag "search[tour.start_date0]", nil, class: 'form-control', value: value_for('search', 'tour.start_date0')
              %span.input-group-addon
                %span.glyphicon.glyphicon-calendar
        .col-md-6
          .form-group
            = label_tag("До")
            .input-group.date.datepicker
              = text_field_tag "search[tour.start_date1]", nil, class: 'form-control', value: value_for('search', 'tour.start_date1')
              %span.input-group-addon
                %span.glyphicon.glyphicon-calendar
      .row
        .col-md-6
          .form-group
            = label_tag(Tour.human_attribute_name(:days_in_tour))
      .row
        .col-md-6
          .form-group
            = label_tag("От")
            = text_field_tag "search[tour.days_in_tour0]", nil, class: 'form-control', value: value_for('search', 'tour.days_in_tour0')
        .col-md-6
          .form-group
            = label_tag("До")
            = text_field_tag "search[tour.days_in_tour1]", nil, class: 'form-control', value: value_for('search', 'tour.days_in_tour1')
      .row
        .col-md-6
          .form-group
            = label_tag(Tour.human_attribute_name(:add_price))
      .row
        .col-md-6
          .form-group
            = label_tag("От")
            = text_field_tag "search[tour.add_price0]", nil, class: 'form-control', value: value_for('search', 'tour.add_price0')
        .col-md-6
          .form-group
            = label_tag("До")
            = text_field_tag "search[tour.add_price1]", nil, class: 'form-control', value: value_for('search', 'tour.add_price1')
      .row
        .col-md-6
          .form-group
            = label_tag(Tour.human_attribute_name(:add_descr))
            = text_field_tag "search[tour.add_descr]", nil, class: 'form-control', value: value_for('search', 'tour.add_descr')
      
  .panel.panel-wave
    .panel-heading
      Маршрут
    .panel-body
      .row
        .col-md-6
          .form-group
            = label_tag(Route.human_attribute_name(:name))
            = text_field_tag "search[route.name]", nil, class: 'form-control', value: value_for('search', 'route.name')
        .col-md-6
          .form-group
            = label_tag(Route.human_attribute_name(:descr))
            = text_field_tag "search[route.descr]", nil, class: 'form-control', value: value_for('search', 'route.descr')
      .row
        .col-md-6
          .form-group
            = label_tag(Route.human_attribute_name(:base_price))
      .row
        .col-md-6
          .form-group
            = label_tag("От")
            = text_field_tag "search[route.base_price0]", nil, class: 'form-control', value: value_for('search', 'route.base_price0')
        .col-md-6
          .form-group
            = label_tag("До")
            = text_field_tag "search[route.base_price1]", nil, class: 'form-control', value: value_for('search', 'route.base_price1')
  .panel.panel-wave
    .panel-heading
      Город
    .panel-body
      .row
        .col-md-6
          .form-group
            = label_tag(City.human_attribute_name(:name))
            = text_field_tag "search[city.name]", nil, class: 'form-control', value: value_for('search', 'city.name')
  = submit_tag "Искать", class: 'btn btn-primary'
  
- if !(@result[0].empty?)
  %br
  %ul Обнаружены параметры:
  - @result[0].each do |r|
    %li= t(r[0]) + ", " +  t(r[1]) + "#{r[2]}" + "#{r[3]}"

  
.page-header
  %h1 Результат поиска

%table.table.table-hover.table-striped
  %thead
    %tr
      %th= Tour.human_attribute_name(:start_date)
      %th= Tour.human_attribute_name(:days_in_tour)
      %th= Tour.human_attribute_name(:route)
      %th= Route.human_attribute_name(:city)
      %th Общая цена
      %th
      
  %tbody
    - @result[1].each do |tour|
      %tr
        %td.center{data: {label: Tour.human_attribute_name(:start_date)}}
          = tour.start_date
        %td.center{data: {label: Tour.human_attribute_name(:days_in_tour)}}
          = tour.days_in_tour
        %td.center{data: {label: Tour.human_attribute_name(:route)}}
          = tour.route.name
        %td.center{data: {label: Route.human_attribute_name(:city)}}
          = tour.route.city.name
        %td.center{data: {label: "Общая цена"}}
          = tour.add_price + tour.route.base_price
        %td.right
          = link_to tour, class: 'btn btn-warning' do
            = fa_icon :eye
            = t('buttons.show')

app/views/tours/show.html.haml
- if is_admin?
  =breadcrumb_tag do
    %li.active
      База данных
    %li
      = link_to 'Туры', tours_path
    %li
      = t('headers.tours.show')

%dl
  %dt= Tour.human_attribute_name(:start_date)
  %dd= @tour.start_date
  %dt= Tour.human_attribute_name(:days_in_tour)
  %dd= @tour.days_in_tour
  %dt= Tour.human_attribute_name(:route)
  .step
    %dt= Route.human_attribute_name(:name)
    %dd= @tour.route.name
    %dt= Route.human_attribute_name(:base_price)
    %dd= @tour.route.base_price
    %dt= Route.human_attribute_name(:city)
    .step
      %dt= City.human_attribute_name(:name)
      %dd= @tour.route.city.name
    %dt= Route.human_attribute_name(:descr)
    %dd= @tour.route.descr
  %dt= Tour.human_attribute_name(:add_price)
  %dd= @tour.add_price
  %dt= Tour.human_attribute_name(:add_descr)
  %dd= @tour.add_descr
  
  %br
  %dd=link_to t('helpers.back'), tours_path, class: 'btn btn-primary'