config/routes.rb
Rails.application.routes.draw do
  resources :tours do
    collection do
      get :search
    end
  end
  resources :routes
  resources :excursions
  resources :cities
  resources :role_users
  resources :roles
  resources :password_resets

  get 'welcome/index', as: :welcome
  get 'welcome/insufficient_privileges', as: :ip
  get 'login' => 'welcome#new', :as => :login
  get 'logout' => 'welcome#destroy', :as => :logout
  post 'try_login' => 'welcome#create', :as => :try_login
  root 'welcome#index'

  resources :users do
    member do
      get :activate
    end
  end

end

app/models/excursion.rb
class Excursion < ActiveRecord::Base
  belongs_to :city
  
  validates :name, presence: true, uniqueness: true
  validates :price, presence: true, numericality: {greater_than_or_equal_to: 1}
  validates :city, presence: true
  validates :descr, presence: true
end

app/controllers/excursions_controller.rb
class ExcursionsController < ApplicationController
  before_action :set_excursion, only: [:show, :edit, :update, :destroy]

  # GET /excursions
  # GET /excursions.json
  def index
    @excursions = Excursion.all
  end

  # GET /excursions/1
  # GET /excursions/1.json
  def show
  end

  # GET /excursions/new
  def new
    @excursion = Excursion.new
  end

  # GET /excursions/1/edit
  def edit
  end

  # POST /excursions
  # POST /excursions.json
  def create
    @excursion = Excursion.new(excursion_params)
    
    flag = true
    if !(params["excursion"]["city_id"].empty?)
      @excursion.city_id = params["excursion"]["city_id"].to_i
    else
      city = City.new
      city.name = params["excursion"]["city"]["name"]
      flag = false if !(city.save)
      @excursion.city = city
    end

    respond_to do |format|
      if flag and @excursion.save
        format.html { redirect_to @excursion, notice: 'Excursion was successfully created.' }
        format.json { render :show, status: :created, location: @excursion }
      else
        format.html { render :new }
        format.json { render json: @excursion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /excursions/1
  # PATCH/PUT /excursions/1.json
  def update
    respond_to do |format|
      if @excursion.update(excursion_params)
        format.html { redirect_to @excursion, notice: 'Excursion was successfully updated.' }
        format.json { render :show, status: :ok, location: @excursion }
      else
        format.html { render :edit }
        format.json { render json: @excursion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /excursions/1
  # DELETE /excursions/1.json
  def destroy
    @excursion.destroy
    respond_to do |format|
      format.html { redirect_to excursions_url, notice: 'Excursion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_excursion
      @excursion = Excursion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def excursion_params
      params.require(:excursion).permit(:name, :price, :descr, :city_id,
        cities_attributes: [:id, :name])
    end
end

app/helpers/excursions_helper.rb
module ExcursionsHelper
end

app/views/excursions/_city_fields.html.haml
.row
  .col-md-6
    .form-group
      = fr.label City.human_attribute_name(:name)
      = fr.text_field :name, class: 'form-control'
      = fr.error_messages_for(:name)

app/views/excursions/_form.html.haml
= form_for @excursion do |f|
  = error_messages_for @excursion
  .row
    .col-md-6
      .form-group
        = f.label :name
        = f.text_field :name, class: 'form-control'
        = f.error_messages_for(:name)
  .row
    .col-md-6
      .form-group
        = f.label :price
        = f.text_field :price, class: 'form-control'
        = f.error_messages_for(:price)
  .panel.panel-wave
    .panel-heading
      Город
    .panel-body
      = f.collection_select :city_id, City.all, :id, :name, {include_blank: true}, {id: 'city_select'}
      = f.error_messages_for(:city_id)
      = f.fields_for :city, f.object.city || f.object.build_city do |fr|
        %fieldset#city-fieldset{"data-content" => "#{render "city_fields", fr: fr}"}
          %div#city-fields
            Выбран существующий город
  .row
    .col-md-6
      .form-group
        = f.label :descr
        = f.text_area :descr, class: 'form-control'
        = f.error_messages_for(:descr)
  .form-actions
    = f.submit nil, class: 'btn btn-primary'

app/views/excursions/edit.html.haml
- if is_admin?
  =breadcrumb_tag do
    %li.active
      База данных
    %li
      = link_to t('activerecord.models.excursions'), excursions_path
    %li
      = link_to(@excursion.name, @excursion)
    %li
      = t('headers.excursions.edit')

  .page-header
    %h1= t('headers.excursions.edit')

  = render 'form'
- else
  %h1= t('helpers.denied')

app/views/excursions/index.html.haml
- if is_admin?
  =breadcrumb_tag do
    %li.active
      База данных
    %li
      = link_to t('activerecord.models.excursions'), excursions_path


.page-header
  %h1= t('headers.excursions.index')

%table.table.table-hover.table-striped
  - if is_admin?
    %caption
      = link_to new_excursion_path, class: 'btn btn-success' do
        = fa_icon :plus
        = t('buttons.new.excursion')  
  %thead
    %tr
      %th= Excursion.human_attribute_name(:name)
      %th= Excursion.human_attribute_name(:price)
      %th= Excursion.human_attribute_name(:city)
      %th= Excursion.human_attribute_name(:descr)
      %th

  %tbody
    - @excursions.each do |excursion|
      %tr
        %td.center{data: {label: Excursion.human_attribute_name(:name)}}
          = excursion.name
        %td.center{data: {label: Excursion.human_attribute_name(:price)}}
          = excursion.price
        %td.center{data: {label: Excursion.human_attribute_name(:city)}}
          = excursion.city.name
        %td.center{data: {label: Excursion.human_attribute_name(:descr)}}
          = excursion.descr
        %td.right
          = link_to excursion, class: 'btn btn-warning' do
            = fa_icon :eye
            = t('buttons.show')
          - if is_admin?
            = link_to edit_excursion_path(excursion), class: 'btn btn-info' do
              = fa_icon :edit
              = t('buttons.edit')
          - if is_admin?
            = link_to excursion, :method => :delete, 
            :data => { :confirm => t('buttons.confirm.excursion') }, 
            class: 'btn btn-danger' do
              = fa_icon :times
              = t('buttons.destroy')

app/views/excursions/new.html.haml
- if is_admin?
  =breadcrumb_tag do
    %li.active
      База данных
    %li
      = link_to t('activerecord.models.excursions'), excursions_path
    %li
      = t('headers.excursions.new')

  .page-header
    %h1= t('headers.excursions.new')

  = render 'form'
- else
  %h1= t('helpers.denied')

app/views/excursions/show.html.haml
- if is_admin?
  =breadcrumb_tag do
    %li.active
      База данных
    %li
      = link_to t('activerecord.models.excursions'), excursions_path
    %li
      = link_to(@excursion.name, @excursion)
    %li
      = t('headers.excursions.show')
    
.page-header
  %h1= t('headers.excursions.show')

%dl
  %dt= Excursion.human_attribute_name(:name)
  %dd= @excursion.name
  %dt= Excursion.human_attribute_name(:price)
  %dd= @excursion.price
  %dt= Excursion.human_attribute_name(:city)
  .step
    %dt= City.human_attribute_name(:name)
    %dd= @excursion.city.name
  %dt= Excursion.human_attribute_name(:descr)
  %dd= @excursion.descr